config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#home"

  get '/auth/github/callback', to: 'authentications#create'

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    resources :road_trips, as: "created_trips"
    resources :destinations
    resources :comments
    resources :pictures
  end
  resources :road_trips do
    resources :destinations, only: [:show, :index]
    resources :comments
    resources :pictures
  end
  resources :destinations do
    resources :tags, only: [:show, :index, :create]
    resources :comments
    resources :pictures
  end
  resources :tags
  resources :user_road_trips, only: [:create]

end

app/models/road_trip.rb
class RoadTrip < ActiveRecord::Base
  validates :name, presence: true
  validates :description, presence: true
  validates :total_miles, presence: true
  validates :author_id, presence: true
  validates_associated :destinations

  has_many :user_road_trips, dependent: :delete_all
  has_many :users, through: :user_road_trips
  has_many :road_trip_destinations, dependent: :delete_all
  has_many :destinations, through: :road_trip_destinations
  has_many :tags, through: :destinations
  has_many :pictures, as: :imageable
  has_many :comments, as: :commentable

  accepts_nested_attributes_for :destinations
  accepts_nested_attributes_for :road_trip_destinations
  accepts_nested_attributes_for :tags

  def author
    User.find(self.author_id) || false
  end

  def set_tags(tags, destination)
    tags.each_value do |name|
      if name != ""
        destination.tags.build(name: name)
      end
    end
  end

  def destinations_attributes=(destination_attributes)
    destination_attributes.values.each do |destination_attribute|
      stop_order = destination_attribute["stop_order"]
      destination_attribute.delete("stop_order")
      tags = destination_attribute["tags_attributes"].first[1]
      destination_attribute.delete("tags_attributes")

      destination = Destination.find_or_initialize_by(destination_attribute)
      set_tags(tags, destination)

      if destination.save
        self.road_trip_destinations.create(destination_id: destination.id, destination_order: stop_order)
      end
    end
  end

  def road_trip_destinations_attributes=(road_trip_destinations_attributes)
    road_trip_destinations_attributes.values.each do |road_trip_destination_attribute|
      if rtd = self.road_trip_destinations.find_by(destination_id: road_trip_destination_attribute["destination_id"])
        rtd.destination_order = road_trip_destination_attribute["destination_order"]
        rtd.save
      else
        self.road_trip_destinations.build(destination_id: road_trip_destination_attribute["destination_id"],
          destination_order: road_trip_destination_attribute["destination_order"])
      end
    end
  end
end

app/controllers/road_trips_controller.rb
class RoadTripsController < ApplicationController
  before_action :set_road_trip, only: [:show, :edit, :update, :destroy]
  before_action :set_destinations, only: [:new, :edit, :update, :create]
  before_action :authorize, only: [:edit, :update, :destroy]

  def index
    if params[:user_id]
      @road_trips = User.find(params[:user_id]).road_trips
    else
      @road_trips = RoadTrip.all
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @road_trips }
    end
  end

  def show
  end

  def new
    @road_trip = RoadTrip.new
  end

  def edit
    if params[:user_id]
      @user = User.find_by(id: params[:user_id])
      if @user.nil?
        redirect_to users_path, alert: "User not found."
      else
        @road_trip = RoadTrip.find_by(id: params[:id], author_id: params[:user_id])
        redirect_to user_created_trips_path(@user), alert: "No trips found." if @road_trip.nil?
      end
    else
      @road_trip = RoadTrip.find(params[:id])
    end
  end

  def create
    @road_trip = RoadTrip.new(road_trip_params)
    if @road_trip.save
      if check_destination
        @road_trip.update(destination_params)
        redirect_to @road_trip
      else
        flash[:error] = "Your new destination must have a name, description, city, state, and street address."
        render :new
      end
    else
      render :new
    end
  end

  def update
    if @road_trip.update(road_trip_params)
      @road_trip.update(destination_params)
      redirect_to @road_trip
    else
      render :edit
    end
  end

  def destroy
    @road_trip.destroy
    redirect_to road_trips_url
  end

  private
    def set_road_trip
      @road_trip = RoadTrip.find(params[:id])
    end

    def set_destinations
      @destinations = Destination.all
    end

    def road_trip_params
      params.require(:road_trip).permit(
        :name, :description, :total_miles, :author_id,
        )
    end

    def destination_params
      cleanse_rtd_attributes
      params.require(:road_trip).permit(
        destinations_attributes: [:name, :description, :city, :state, :street_address, :author_id, :stop_order,
          tags_attributes: [:tag_1, :tag_2, :tag_3]],
        road_trip_destinations_attributes: [:destination_id, :destination_order]
      ) # you also capture destination_ids [], but are only using them in the cleanse function
    end

    def authorize
      if current_user.id != @road_trip.author_id && !current_user.admin
        flash[:error] = "You can only edit trips you have created."
        redirect_to @road_trip
      end
    end

    def check_destination
      !(params[:road_trip][:destinations_attributes]["0"].values[0..5].include?("") && params[:road_trip][:destinations_attributes]["0"].values[0..5].find{|e| /\S/ =~ e})
    end

    def cleanse_rtd_attributes
      if params[:road_trip][:destination_ids]
        params[:road_trip][:road_trip_destinations_attributes].values.each_with_index do |rtd, i|
          if !params[:road_trip][:destination_ids].include?(rtd["destination_id"])
            params[:road_trip][:road_trip_destinations_attributes].delete("#{i}")
          end
        end
      else
        params[:road_trip][:road_trip_destinations_attributes].values.each_with_index {|rtd, i|
          params[:road_trip][:road_trip_destinations_attributes].delete("#{i}")
        }
      end
    end
end

app/helpers/road_trips_helper.rb
module RoadTripsHelper
  def completed?(road_trip)
    if trip = UserRoadTrip.find_by(road_trip_id: road_trip.id, user_id: current_user.id)
      if trip.status == "Completed"
        return true
      end
    end
  end

  def in_process?(road_trip)
    if trip = UserRoadTrip.find_by(road_trip_id: road_trip.id, user_id: current_user.id)
      if trip.status == "In Process"
        return true
      end
    end
  end

  def trip_author(road_trip)
    User.find(road_trip.author_id)
  end
end

app/views/road_trips/_destination_fields.html.erb
<%= f.label :stop_order %>
<%= f.number_field :stop_order %><br>
<%= f.label :name %>
<%= f.text_field :name %><br>
<%= f.label :description %>
<%= f.text_area :description, size: "75x5" %>
<%= f.label :city %>
<%= f.text_field :city %> ,
<%= f.label :state %>
<%= f.text_field :state %><br>
<%= f.label :street_address %>
<%= f.text_field :street_address %><br><br>
<h6 class="card-subtitle text-muted">Add a descriptive tag or two to this destination, so people know what this place is like.</h6><br>
<%= f.fields_for :tags, f.object.tags.build do |tags_fields| %>
  <%= render 'tag_fields', f: tags_fields %>
<% end %>
<%= f.hidden_field :author_id, value: current_user.id %>

app/views/road_trips/_form.html.erb
<div class="card mb-3">
  <%= form_for(@road_trip) do |f| %>
  <div class="card mb-3" style="height: 100%; width:46%; float:left; margin:1px">
    <div class="card-body">
      <%= render partial: 'layouts/form_errors', locals: { model: @road_trip } %>

      <%= f.hidden_field :author_id, value: @user.id %>

      <div class="form-group">
        <%= f.label :name %><br>
        <%= f.text_field :name, size: "70" %>
      </div>
      <br>
      <div class="form-group">
        <%= f.label :description %><br>
        <%= f.text_area :description, size: "70x5" %>
      </div>
      <br>
      <div class="form-group">
        <%= f.label :total_miles %><br>
        <%= f.number_field :total_miles %>
      </div>
    </div>

    <div class="card-body">
      <h3 class="card-header">Create A New Destination</h3><br>
      <%= f.fields_for :destinations, @road_trip.destinations.build do |destinations_fields| %>
        <%= render 'destination_fields', f: destinations_fields %>
      <% end %>
    </div>
  <br>
</div>

  <div class="card mb-3" style="height: 100%; width:52%; float:right; margin:1px">
    <h3 class="card-header">Add Destinations</h3>
    <div class="card-body">
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">City, State</th>
            <th scope="col">Add/Remove</th>
            <th scope="col"><center>Order</center></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @destinations.each.with_index(1) do |destination, i| %>
            <%= f.fields_for :road_trip_destinations, @road_trip.road_trip_destinations.build(destination_id: destination.id) do |rtds_fields| %>
              <% if rtds_fields.object.destination_order = destination.on_this_trip?(@road_trip) %>
                <tr class="table-success">
                  <td><%= destination.name %></td>
                  <td><%= destination.city_and_state %></td>
                  <td><center><input type="checkbox" value="<%=i%>" name="road_trip[destination_ids][]" id="road_trip_destination_ids_<%=i%>" checked></input></center></td>
                  <td><center><%= rtds_fields.number_field :destination_order, style: 'width: 50%;' %></center></td>
                  <%= rtds_fields.hidden_field :destination_id %>
                </tr>
              <% else %>
                <tr class="table-active">
                  <td><%= destination.name %></td>
                  <td><%= destination.city_and_state %></td>
                  <td><center><input type="checkbox" value="<%=i%>" name="road_trip[destination_ids][]" id="road_trip_destination_ids_<%=i%>"></input></center></td>
                  <td><center><%= rtds_fields.number_field :destination_order,  style: 'width: 50%;' %></center></td>
                  <%= rtds_fields.hidden_field :destination_id %>
                </tr>
              <% end %>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary btn-lg btn-block"%>
    <% end %>
  </div>
</div>

app/views/road_trips/_urt_buttons.html.erb
<% if !in_process?(road_trip) && !completed?(road_trip) %>
  <%= render partial: "user_road_trips/in_process", locals: {user_road_trip: road_trip.user_road_trips.build} %>
<% end %>
<br>
<% if !completed?(road_trip) %>
  <%= render partial: "user_road_trips/completed", locals: {user_road_trip: road_trip.user_road_trips.build} %>
<% end %>

app/views/road_trips/index.html.erb
<h1><%= link_to "Road Trips", road_trips_path, style: "text-decoration:none;" %> <%= link_to 'Create New Road Trip', new_user_created_trip_path(current_user), {class: "btn btn-primary"} %> </h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Status</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Miles</th>
      <th scope="col">Destinations</th>
      <th scope="col" colspan="3"><center>Controls</center></th>
    </tr>
  </thead>
  <tbody>
    <% @road_trips.each do |road_trip| %>
      <tr class="table-active">
        <td>
          <% if current_user.road_trips.include?(road_trip) %>
            <%= render partial: "users/badges", locals: {road_trip: road_trip} %>
          <% end %>
        </td>
        <td><%= link_to road_trip.name, road_trip_path(road_trip) %></td>
        <td><%= road_trip.description %></td>
        <td><%= road_trip.total_miles %></td>
        <td><center><%= link_to road_trip.destinations.count, road_trip_destinations_path(road_trip) %></center></td>
        <% if current_user.admin || road_trip.author_id == current_user.id %>
          <%= render partial: "users/admin/controls", locals: {model: road_trip} %>
        <% else %>
          <% if !current_user.road_trips.empty? %>
            <td colspan="3"></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "All Users", users_path %>
<br><br><br>

app/views/road_trips/show.html.erb
<div class="card mb-3">
  <h3 class="card-header">
    <span style="float:left;"><%= @road_trip.name %></span>
    <span style="float:right;"><%= @road_trip.total_miles %> Miles</span>
  </h3>

  <div class="card-body">
    <h5 class="card-title">By: <%= @road_trip.author.name %></h5>
    <h6 class="card-subtitle text-muted">Created At: <%= @road_trip.created_at %> </h6>
  </div>

  <div class="card-body">
    <div class="form-group" style="float:left;">
      <% if !@road_trip.pictures.empty? %>
        <img style="height: 200px; width: 400px; display: block; float:left;" src="<%=@road_trip.pictures[0].url%>" alt="Card image" class="image_url">
        <a href="<%=@road_trip.id%>/pictures" class="js-next-pic" data-id="0">next</a> / <a href="<%=@road_trip.id%>/pictures" class="js-previous-pic" data-id="0">previous</a>
        <span class="js-page-count">(1)<span>
      <% else %>
        <center><a href="#" class="add_picture"><img style="height: 200px; width: 400px; display: block; float:left;" src="http://placeholder.pics/svg/400x200/8B8B8B/FFFFFF/Add%20a%20Picture"></a></center>
      <% end %>
    </div>
    <div class="form-group" style="float:right;">
      <%= render partial: "users/badges", locals: {road_trip: @road_trip} %>
      <br>
      <%= render partial: "user_road_trips/buttons", locals: {road_trip: @road_trip} %>
      <br>
    </div>
  </div>

  <div class="container" role="main">

    <div class="card-body">
      <p class="card-text"><%= @road_trip.description %></p>
    </div>

    <ul class="list-group list-group-flush">
      <% @road_trip.road_trip_destinations.order(:destination_order).each do |road_trip_destination| %>
        <li class="list-group-item"><%= link_to road_trip_destination.destination.name, destination_path(road_trip_destination.destination), { style: "float:left;" } %>
          <span class="badge badge-primary" style="float:right;">Stop <%= road_trip_destination.destination_order %></span></li>
      <% end %>
    </ul>

    <div class="card-body">|
      <% @road_trip.tags.uniq.each do |tag| %>
        <%= link_to tag.name, tag_path(tag) %> |
      <% end %>
    </div>

    <%= render partial: 'comments/form', locals: { model: @road_trip } %>

    <div class="card-footer text-muted">
      Last Updated At: <%= @road_trip.updated_at %> |
      <% if current_user.id == @road_trip.author_id %>
        <%= link_to 'Edit', edit_user_created_trip_path(current_user, @road_trip) %> |
      <% end %>

      <%= link_to 'All Road Trips', road_trips_path %>
    </div>

  </div>
</div>