config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#home"

  get '/auth/github/callback', to: 'authentications#create'

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    resources :road_trips, as: "created_trips"
    resources :destinations
    resources :comments
    resources :pictures
  end
  resources :road_trips do
    resources :destinations, only: [:show, :index]
    resources :comments
    resources :pictures
  end
  resources :destinations do
    resources :tags, only: [:show, :index, :create]
    resources :comments
    resources :pictures
  end
  resources :tags
  resources :user_road_trips, only: [:create]

end

app/models/user.rb
class User < ActiveRecord::Base
  before_destroy :destroy_authored_trips, :destroy_authored_destinations
  scope :road_warriors, -> {all.order(miles_driven: :desc)}

  belongs_to :current_trip, class_name: 'RoadTrip', foreign_key: 'current_trip_id'
  has_many :user_road_trips, dependent: :delete_all
  has_many :road_trips, through: :user_road_trips
  has_many :pictures, as: :imageable
  #has_many :comments, as: :commentable

  accepts_nested_attributes_for :user_road_trips

  validates :name, presence: true
  validates :email, presence: true
  has_secure_password

  def trips_created
    RoadTrip.where(author_id: self.id)
  end

  def destinations_created
    Destination.where(author_id: self.id)
  end

  def user_road_trips_attributes=(user_road_trip_attributes)
    user_road_trip_attributes.values.each do |user_road_trip_attribute|
      user_road_trip = UserRoadTrip.find_or_initialize_by(road_trip_id: user_road_trip_attribute["road_trip_id"], user_id: self.id)
      user_road_trip.completed = user_road_trip_attribute["completed"]
      user_road_trip.save
    end
  end

  private
    def destroy_authored_trips
      RoadTrip.where(author_id: self.id).destroy_all
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authorize, only: [:edit, :update, :destroy]
  skip_before_action :require_login, only: [:new, :create]

  def index
    if current_user.admin
      @users = User.all
    else
      @users = User.road_warriors
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url
  end

  private
    # def set_user
    #   @user = User.find(params[:id])
    # end

    def user_params
      params.require(:user).permit(:name, :email, :password, :current_trip_id, user_road_trips_attributes: [:completed, :road_trip_id])
    end

    def authorize
      if current_user.id != params[:id].to_i && !current_user.admin
        flash[:error] = "You can only edit your own account."
        redirect_to @user
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def edit_path(model)
    "edit_" + model.class.name.split(/(?=[A-Z])/).join('_').downcase + "_path"
  end
end

app/views/users/_badges.html.erb
<% if in_process?(road_trip) %>
  <span class="badge badge-pill badge-warning">In Process</span>
<% end %>
<% if completed?(road_trip) %>
  <span class="badge badge-pill badge-success">Completed</span>
<% end %>

app/views/users/_form.html.erb
<br /><center><div class="jumbotron" style="height:50%; width:50%;">
  <%= form_for @user do |f| %>
    <%= render partial: 'layouts/form_errors', locals: { model: @user } %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
  <br>
  <% if logged_in? %>
    <%= link_to 'Back', user_path(@user) %>
  <% else %>
    <%= link_to 'Back', root_path %>
  <% end %>
</div></center>

app/views/users/edit.html.erb
<center><h1>Edit Your Account</h1></center>

  <%= render 'form' %>
<br>
<center><%= button_to 'Delete Account', @user, class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } if current_user.admin || current_user == @user  %></center>

app/views/users/index.html.erb
<h1>Road Warriors</h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">User</th>
      <th scope="col">Miles Driven</th>
      <th scope="col">Current Trip</th>
      <th scope="col">Trips Created</th>
      <% if current_user.admin %>
        <th colspan=3>Controls</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <% if (!current_user.admin && !user.admin) || current_user.admin %>
        <tr class="table-active">
          <th scope="row"><%= link_to user.name, user_path(user) %></td>
          <td><%= user.miles_driven %></td>
          <td><%= link_to user.current_trip.name, road_trip_path(user.current_trip) if user.current_trip_id %></td>
          <td><%= link_to user.road_trips.count, user_created_trips_path(user)  if user.road_trips.count > 0 %></td>
          <% if current_user.admin %>
            <%= render partial: "users/admin/controls", locals: {model: user} %>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br>

app/views/users/new.html.erb
<center><h1>Create New Account</h1></center>

  <%= render 'form' %>

app/views/users/show.html.erb
<div class="card mb-3">
  <h3 class="card-header"><%= @user.name %></h3>
  <div class="card-body">
    <h5 class="card-title"><%= @user.miles_driven %> Miles Driven</h5>
    <h6 class="card-subtitle text-muted"><%= @user.user_road_trips.size %> Trip(s) Taken</h6>
  </div>
  <div class="container" role="main">
    <% if !@user.pictures.empty? %>
      <center>
        <span><img style="height: 200px; width: 400px; display: block;" src="<%=@user.pictures[0].url%>" alt="Card image" class="image_url"></span>
        <span><a href="<%=@user.id%>/pictures" class="js-next-pic" data-id="0">next</a> / <a href="<%=@user.id%>/pictures" class="js-previous-pic" data-id="0">previous</a> / </span>
        <span class="js-page-count">(1)<span>
      </center>
    <% else %>
      <center><a href="#" class="add_picture"><img style="height: 200px; width: 400px; display: block;" src="http://placeholder.pics/svg/400x200/8B8B8B/FFFFFF/Add%20a%20Picture"></a></center>
    <% end %>
    <div class="card-body">
      <p class="card-text">Trips Taken:</p>
    </div>
    <ul class="list-group list-group-flush">
      <% if @user.user_road_trips.empty? %>
        <li class="list-group-item">No Trips Taken</center></li>
      <% end %>
      <% @user.user_road_trips.each do |user_road_trip| %>
        <li class="list-group-item"><%= link_to user_road_trip.road_trip.name, road_trip_path(user_road_trip.road_trip) %>
          <div style="float:right;"><%= render partial: "users/badges", locals: {road_trip: user_road_trip.road_trip}, style:"float:right;" %></div>
        </li>
      <% end %>
    </ul>
    <div class="card-body">
      <p class="card-text">Trips Created:</p>
    </div>
    <ul class="list-group list-group-flush">
      <% if @user.trips_created.empty? %>
        <li class="list-group-item"><center><%= link_to "Create a Trip!", new_user_created_trip_path(@user) %></center></li>
      <% end %>
      <% @user.trips_created.each do |trip| %>
        <li class="list-group-item"><%= link_to trip.name, user_created_trip_path(@user, trip) %></li>
      <% end %>
    </ul>
    <div class="card-body">
      <p class="card-text">Destinations Created:</p>
    </div>
    <ul class="list-group list-group-flush">
      <% if @user.destinations_created.empty? %>
        <li class="list-group-item"><center><%= link_to "Create a Destination!", new_user_destination_path(@user) %></center></li>
      <% end %>
      <% @user.destinations_created.each do |destination| %>
        <li class="list-group-item"><%= link_to destination.name, user_destination_path(@user, destination) %></li>
      <% end %>
    </ul>
    <div class="card-body">
      <%= link_to "Comments Made", user_comments_path(@user), id: "comments_made" %> |
      <a href="#" class="card-link" id="comments_received">Comments Received</a>
    </div>
    <div class="comments">
      <ul>
      </ul>
    </div>
    <div class="card-footer text-muted">
      Road Warrior Since: <%= @user.created_at %> |
      <% if current_user.admin || current_user == @user %>
        <%= link_to 'Edit', edit_user_path(@user) %> |
      <% end %>
      <%= link_to 'Rankings', users_path %>
    </div>
  </div>
</div>