config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#home"

  get '/auth/github/callback', to: 'authentications#create'

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    resources :road_trips, as: "created_trips"
    resources :destinations
    resources :comments
    resources :pictures
  end
  resources :road_trips do
    resources :destinations, only: [:show, :index]
    resources :comments
    resources :pictures
  end
  resources :destinations do
    resources :tags, only: [:show, :index, :create]
    resources :comments
    resources :pictures
  end
  resources :tags
  resources :user_road_trips, only: [:create]

end

app/models/destination.rb
class Destination < ActiveRecord::Base
  attr_accessor :stop_order, :tags_attributes

  validates :name, presence: true
  validates :description, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :street_address, presence: true
  validates :street_address, uniqueness: true
  validates :author_id, presence: true

  has_many :destination_tags, dependent: :delete_all
  has_many :tags, through: :destination_tags
  has_many :road_trip_destinations, dependent: :delete_all
  has_many :road_trips, through: :road_trip_destinations
  has_many :users, through: :road_trips
  has_many :pictures, as: :imageable
  has_many :comments, as: :commentable

  accepts_nested_attributes_for :tags

  def city_and_state
    "#{self.city}, #{self.state}"
  end

  def on_this_trip?(road_trip)
    rtd = RoadTripDestination.where(road_trip_id: road_trip.id).where(destination_id: self.id)
    if !rtd.empty?
      rtd.first.destination_order
    end
  end

  def tags_attributes=(tag_attributes)
    tag_attributes.values.each do |tag_attribute|
      tag_attribute.each_value do |name|
        if name != ""
          self.tags.build(name: title)
        end
      end
    end
  end
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]
  before_action :authorize, only:[:edit, :update, :destroy]

  def index
    if params[:road_trip_id]
      @destinations = RoadTrip.find(params[:road_trip_id]).destinations
    else
      @destinations = Destination.all
    end
  end

  def show
  end

  def new
    @destination = Destination.new(author_id: params[:author_id])
  end

  def edit
    if params[:user_id]
      @user = User.find_by(id: params[:user_id])
      if @user.nil?
        redirect_to users_path, alert: "User not found."
      else
        @destination = Destination.find_by(id: params[:id], author_id: params[:user_id])
        redirect_to user_created_trips_path(@user), alert: "No destinations found." if @destination.nil?
      end
    else
      @destination = Destination.find(params[:id])
    end
  end

  def create
    @destination = Destination.new(destination_params)

    if @destination.save
      redirect_to @destination
    else
      render :new
    end
  end

  def update
    if @destination.update(destination_params)
      redirect_to @destination
    else
      render :edit
    end
  end

  def destroy
    @destination.destroy
    redirect_to destinations_url
  end

  private
    def set_destination
      @destination = Destination.find(params[:id])
    end

    def destination_params
      params.require(:destination).permit(:name, :description, :city, :state, :street_address, :author_id, tag_ids:[], tags_attributes: [:tag_1, :tag_2, :tag_3])
    end

    def authorize
      if @destination.author_id != current_user.id && !current_user.admin
        flash[:error] = "You can only edit destinations you've created."
        redirect_to @destination
      end
    end
end

app/views/destinations/_tag_form.html.erb
<!-- <div class="card-body" id="tag_card">
  <%= render partial: 'layouts/form_errors', locals: { model: destination.tags.build} %>
  <%= form_for([destination, destination.tags.build]) do |f| %>
    <%= f.text_field :name %>
    <%= f.submit %>
  <% end %>
</div> -->

app/views/destinations/edit.html.erb
<h1>Edit Destination</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/index.html.erb
<h1><%= link_to "Destinations", destinations_path, style: "text-decoration:none;" %> <%= link_to 'Create New Destination', new_user_destination_path(current_user), {class: "btn btn-primary"} %> </h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">City, State</th>
      <th scope="col">Tags</th>
      <th colspan=3><center>Controls</center></th>
    </tr>
  </thead>
  <tbody>
    <% @destinations.each do |destination| %>
      <tr class="table-active">
        <th scope="row"><%= link_to destination.name, destination_path(destination) %></th>
        <td><%= destination.description %></td>
        <td><%= destination.city_and_state %></td>
        <td><%= link_to destination.tags.count, destination_tags_path(destination) if destination.tags.count > 0 %></td>
        <% if current_user.admin || destination.author_id == current_user.id %>
          <%= render partial: "users/admin/controls", locals: {model: destination} %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "All Trips", road_trips_path %>
<br><br><br>

app/views/destinations/new.html.erb
<h1>New Destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
<div class="card mb-3">
  <h3 class="card-header"><%= @destination.name %></h3>
  <div class="card-body">
    <h5 class="card-title"><%= @destination.city_and_state %></h5>
    <h6 class="card-subtitle text-muted"><%= @destination.street_address %></h6>
  </div>
  <div class="container" role="main">
    <% if !@destination.pictures.empty? %>
      <center>
        <span><img style="height: 200px; width: 400px; display: block;" src="<%=@destination.pictures[0].url%>" alt="Card image" class="image_url"></span>
        <span><a href="<%=@destination.id%>/pictures" class="js-next-pic" data-id="0">next</a> / <a href="<%=@destination.id%>/pictures" class="js-previous-pic" data-id="0">previous</a></span>
        <span class="js-page-count">(1)<span>
      </center>
    <% else %>
      <center><a href="#" class="add_picture"><img style="height: 200px; width: 400px; display: block;" src="http://placeholder.pics/svg/400x200/8B8B8B/FFFFFF/Add%20a%20Picture"></a></center>
    <% end %>
    <div class="card-body">
      <p class="card-text"><%= @destination.description %></p>
    </div>
    <p>Tags:</p>
    <ul class="list-group list-group-flush tags-list">
      <% if @destination.tags.empty? %>
        <li class="list-group-item"><center>None</center></li>
      <% else %>
        <% @destination.tags.each do |tag| %>
          <li class="list-group-item"><%= link_to tag.name, tag_path(tag) %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
  <%#= render partial: 'tag_form', locals: { destination: @destination } %>

  <%= render partial: 'comments/form', locals: { model: @destination } %>

  <div class="card-footer text-muted">
    Created At: <%= @destination.created_at %> |
    <% if current_user.admin || @destination.author_id == current_user.id %>
      <%= link_to 'Edit', edit_user_destination_path(current_user, @destination) %> |
    <% end %>
      <%= link_to 'All Destinations', destinations_path %>
  </div>
</div>