config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#home"

  get '/auth/github/callback', to: 'authentications#create'

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    resources :road_trips, as: "created_trips"
    resources :destinations
    resources :comments
    resources :pictures
  end
  resources :road_trips do
    resources :destinations, only: [:show, :index]
    resources :comments
    resources :pictures
  end
  resources :destinations do
    resources :tags, only: [:show, :index, :create]
    resources :comments
    resources :pictures
  end
  resources :tags
  resources :user_road_trips, only: [:create]

end

app/views/layouts/_errors.html.erb
<% if error %>
  <div class="alert alert-dismissible alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong><%= error %></strong>
  </div>
<% end %>

app/views/layouts/_form_errors.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-dismissible alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong><%= pluralize(model.errors.count, "error") %> prohibited this post from being saved:</strong>

    <ul>
    <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Journey", root_url, {class: "navbar-brand"} %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
      <% if current_user.id %>
        <li class="nav-item active">
          <%= link_to "Road Warriors", users_path, {class: "nav-link"} %>
        </li>
        <li class="nav-item">
          <%= link_to "All Trips", road_trips_path, {class: "nav-link"} %>
        </li>
        <li class="nav-item">
          <%= link_to "Destinations", destinations_path, {class: "nav-link"} %>
        </li>
        <li class="nav-item">
          <%= link_to "Tags", tags_path, {class: "nav-link"} %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %></a>
          <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; transform: translate3d(0px, 44px, 0px); top: 0px; left: 0px; will-change: transform;">
            <%= link_to "Select a Road Trip", road_trips_path, { class: "dropdown-item" } if current_user.current_trip.nil? %>
            <%= link_to "Current Trip", road_trip_path(current_user.current_trip), { class: "dropdown-item" } if current_user.current_trip %>
            <%= link_to "Profile", user_path(current_user), { class: "dropdown-item" } %>
            <%= link_to "Account", edit_user_path(current_user), { class: "dropdown-item" } %>
            <div class="dropdown-divider"></div>
            <%= link_to "Log Out", logout_path, { method: :delete, class: "dropdown-item" } %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Journey</title>
  <link rel="stylesheet" href="https://bootswatch.com/4/sketchy/bootstrap.min.css">
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.4/dist/leaflet.css"
  integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
  crossorigin=""/>
  <link href='https://api.mapbox.com/mapbox-gl-js/v0.49.0/mapbox-gl.css' rel='stylesheet' />
  <script src="https://unpkg.com/leaflet@1.3.4/dist/leaflet.js"
    integrity="sha512-nMMmRyTVoLYqjP9hrbed9S+FzjZHW5gY1TWCHA5ckwXZBadntCNs8kEqAWdrb9O7rxbCaA4lKTIWjDXZxflOcA=="
    crossorigin=""></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>
  <%= render 'layouts/header' %>
  <br>
  <div class="container" role="main">
    <%= render partial: "layouts/errors", locals: {error: flash[:error]} %>
  </div>
  <br>
  <div class="container" role="main">
    <%= yield %>
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
</body>
</html>
<!-- <div class="container">
  <div class="square square1"></div>
  <div class="square square2"></div>
  <div class="square square3"></div>
  <div class="square square4"></div>
  <div class="square square5"></div>
</div> -->